name: Create new release

on:
  push:
    tags:
      - v**

jobs:
  build-docker-image:
    name: Build release Docker image
    uses: ./.github/workflows/docker.yml
    secrets: inherit

  build-helm-chart:
    runs-on: ubuntu-latest
    needs: [build-docker-image] # otherwise you might install a latest helm chart and get image pull error
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Write release version
        id: version
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo Version: $VERSION
          echo "VERSION=$VERSION" >> "$GITHUB_OUTPUT"
      - name: Push helm chart
        uses: appany/helm-oci-chart-releaser@v0.3.0
        with:
          name: restate-operator-helm
          repository: restatedev
          tag: ${{ steps.version.outputs.VERSION }}
          registry: ghcr.io
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}

  publish-release:
    name: Publish release
    runs-on: ubuntu-latest
    needs: [build-docker-image, build-helm-chart]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          # create a draft release which needs manual approval
          draft: true
          files: |
            crd/restatedeployments.yaml
            crd/restateclusters.yaml
